"""Baseline core schema: users, entries, emotion_analyses, diaries

Revision ID: 0001
Revises:
Create Date: 2026-07-08 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - create core diary tables."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    # Create entries table
    op.create_table('entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('input_type', sa.String(length=20), nullable=False),
        sa.Column('raw_content', sa.Text(), nullable=False),
        sa.Column('source_language', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('audio_file_url', sa.String(length=500), nullable=True),
        sa.Column('duration_seconds', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entries_id'), 'entries', ['id'], unique=False)
    op.create_index(op.f('ix_entries_user_id'), 'entries', ['user_id'], unique=False)

    # Create emotion_analyses table
    op.create_table('emotion_analyses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('entry_id', sa.Integer(), nullable=False),
        sa.Column('provider', sa.String(length=50), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=False),
        sa.Column('primary_emotion', sa.String(length=30), nullable=False),
        sa.Column('secondary_emotions', sa.Text(), nullable=False),
        sa.Column('emotion_score', sa.Integer(), nullable=False),
        sa.Column('valence', sa.Float(), nullable=False),
        sa.Column('arousal', sa.Float(), nullable=False),
        sa.Column('intensity', sa.Float(), nullable=False),
        sa.Column('risk_level', sa.String(length=20), nullable=False),
        sa.Column('risk_reason', sa.Text(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=False),
        sa.Column('suggestion', sa.Text(), nullable=False),
        sa.Column('raw_response_json', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entry_id', )
    )
    op.create_index(op.f('ix_emotion_analyses_id'), 'emotion_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_emotion_analyses_entry_id'), 'emotion_analyses', ['entry_id'], unique=False)

    # Create diaries table
    op.create_table('diaries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('entry_id', sa.Integer(), nullable=False),
        sa.Column('analysis_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=120), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('diary_date', sa.Date(), nullable=False),
        sa.Column('is_favorite', sa.Boolean(), nullable=False),
        sa.Column('visibility', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['analysis_id'], ['emotion_analyses.id'], ),
        sa.ForeignKeyConstraint(['entry_id'], ['entries.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('analysis_id', name='uq_diaries_analysis_id'),
        sa.UniqueConstraint('entry_id', name='uq_diaries_entry_id')
    )
    op.create_index(op.f('ix_diaries_id'), 'diaries', ['id'], unique=False)
    op.create_index(op.f('ix_diaries_user_id'), 'diaries', ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - drop core diary tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diaries_user_id'), table_name='diaries')
    op.drop_index(op.f('ix_diaries_id'), table_name='diaries')
    op.drop_table('diaries')
    op.drop_index(op.f('ix_emotion_analyses_entry_id'), table_name='emotion_analyses')
    op.drop_index(op.f('ix_emotion_analyses_id'), table_name='emotion_analyses')
    op.drop_table('emotion_analyses')
    op.drop_index(op.f('ix_entries_user_id'), table_name='entries')
    op.drop_index(op.f('ix_entries_id'), table_name='entries')
    op.drop_table('entries')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
