"""Add chat schema: conversations, messages, message_sources

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-08 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - create chat tables."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Create conversations table
    op.create_table('conversations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('mode', sa.String(length=20), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('anchor_diary_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('deleted_at', sa.DateTime(), nullable=True),
        sa.CheckConstraint("mode IN ('companion', 'past_self')", name='ck_conversation_mode'),
        sa.CheckConstraint(
            "(mode = 'companion' AND anchor_diary_id IS NULL) OR (mode = 'past_self' AND anchor_diary_id IS NOT NULL)",
            name='ck_conversation_mode_anchor'
        ),
        sa.ForeignKeyConstraint(['anchor_diary_id'], ['diaries.id'], ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_user_deleted_updated', 'conversations', ['user_id', 'deleted_at', 'updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_anchor_diary_id'), 'conversations', ['anchor_diary_id'], unique=False)
    op.create_index(op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_updated_at'), 'conversations', ['updated_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)

    # Create messages table
    op.create_table('messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('conversation_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('retrieval_used', sa.Boolean(), nullable=False),
        sa.Column('model_name', sa.String(length=100), nullable=True),
        sa.Column('latency_ms', sa.Integer(), nullable=True),
        sa.Column('token_usage_input', sa.Integer(), nullable=True),
        sa.Column('token_usage_output', sa.Integer(), nullable=True),
        sa.Column('error_code', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_message_role'),
        sa.CheckConstraint("status IN ('pending', 'completed', 'failed')", name='ck_message_status'),
        sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conv_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)

    # Create message_sources table
    op.create_table('message_sources',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('message_id', sa.Integer(), nullable=False),
        sa.Column('diary_id', sa.Integer(), nullable=True),
        sa.Column('source_type', sa.String(length=20), nullable=False),
        sa.Column('diary_date_snapshot', sa.Date(), nullable=True),
        sa.Column('title_snapshot', sa.String(length=120), nullable=False),
        sa.Column('excerpt_snapshot', sa.Text(), nullable=False),
        sa.Column('emotion_label_snapshot', sa.String(length=30), nullable=True),
        sa.Column('relevance_score', sa.Float(), nullable=False),
        sa.Column('rank', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.CheckConstraint("source_type IN ('anchor', 'retrieved')", name='ck_source_type'),
        sa.CheckConstraint('rank >= 1', name='ck_rank'),
        sa.CheckConstraint('relevance_score >= 0.0 AND relevance_score <= 1.0', name='ck_relevance_score'),
        sa.ForeignKeyConstraint(['diary_id'], ['diaries.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('message_id', 'diary_id', name='uq_message_source_message_diary'),
        sa.UniqueConstraint('message_id', 'rank', name='uq_message_source_message_rank')
    )
    op.create_index(op.f('ix_message_sources_diary_id'), 'message_sources', ['diary_id'], unique=False)
    op.create_index(op.f('ix_message_sources_id'), 'message_sources', ['id'], unique=False)
    op.create_index(op.f('ix_message_sources_message_id'), 'message_sources', ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - drop chat tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_sources_message_id'), table_name='message_sources')
    op.drop_index(op.f('ix_message_sources_id'), table_name='message_sources')
    op.drop_index(op.f('ix_message_sources_diary_id'), table_name='message_sources')
    op.drop_table('message_sources')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_messages_conv_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_updated_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_anchor_diary_id'), table_name='conversations')
    op.drop_index('idx_conversations_user_deleted_updated', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
